project:
  type: book
  pre-render:
    - make kernel
  post-render:
    - quarto convert chapters/references.qmd
    - make post-render

book:
  title: "Earth Observation Datascience"
  author:
    - Wolfgang Wagner
    - Nikolas Pikall
    - Martin Schobben
    - Joseph Wagner
    - Davide Festa
    - Felix David Reuß
    - Luka Jovic
  date: "`python -c \"import datetime; print(datetime.datetime.now())\"`"
  chapters:
    - index.qmd
    - part: chapters/courses/microwave-remote-sensing.qmd
      chapters:
        - chapters/courses/microwave-remote-sensing/01_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/02_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/03_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/04_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/05_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/06_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/07_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/08_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/09_in_class_exercise.qmd
  appendices:
    - part: "Templates"
      chapters:
        - chapters/templates/classification.qmd
    - part: "Tutorials"
      chapters:
        - chapters/tutorials/floodmapping.qmd
    - chapters/references.qmd
  navbar:
    logo: chapters/images/logos/tuw-geo_eodc_logo_horizontal.png
  sidebar:
    logo: chapters/images/logos/tuw-geo_eodc_logo_vertical.png
bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#006699"
    title-block-banner-color: white

execute:
  freeze: auto
  cache: true
  keep-ipynb: true