project:
  type: book
  pre-render:
    - make kernel
  post-render: make post-render

book:
  title: "Earth Observation Datascience"
  author: ""
  date: "7/10/2024"
  chapters:
    - index.qmd
    - part: "chapters/courses/Microwave-remote-sensing.qmd"
      chapters:
        - chapters/courses/microwave-remote-sensing/01_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/02_in_class_exercise.qmd
  appendices:
    - part: "Templates"
      chapters:
        - chapters/templates/Classification.qmd
    - part: "Tutorials"
      chapters:
        - chapters/tutorials/Floodmapping.qmd
    - chapters/references.qmd
  navbar:
    logo: assets/images/tuw-geo_eodc_logo_horizontal.png
  sidebar:
    logo: assets/images/tuw-geo_eodc_logo_vertical.png
bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#006699"
    title-block-banner-color: white

execute:
  freeze: auto
  cache: true
  keep-ipynb: true