project:
  type: book
  pre-render:
    - make kernel
  post-render:
    - quarto convert chapters/references.qmd
    - make post-render

book:
  title: "Earth Observation Datascience"
  author:
    - Wolfgang Wagner
    - Nikolas Pikall
    - Martin Schobben
    - Joseph Wagner
    - Davide Festa
    - Felix David Reuß
    - Luka Jovic
  date: "5 May 2025"
  chapters:
    - index.qmd
    - part: chapters/courses/microwave-remote-sensing.qmd
      chapters:
        - chapters/courses/microwave-remote-sensing/unit_01/01_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_01/02_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_01/03_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_02/04_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_02/05_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_02/06_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_03/07_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_03/08_in_class_exercise.qmd
        - chapters/courses/microwave-remote-sensing/unit_03/09_in_class_exercise.qmd
    - part: chapters/courses/environmental-remote-sensing.qmd
      chapters:
        - chapters/courses/environmental-remote-sensing/mozambique-droughts.qmd
  appendices:
    - part: chapters/templates/prereqs-templates.qmd
      chapters:
        - chapters/templates/classification.qmd
    - part: chapters/tutorials/prereqs-tutorials.qmd
      chapters:
        - chapters/tutorials/floodmapping.qmd
        - chapters/tutorials/harmonic-parameters.qmd
    - chapters/references.qmd
  navbar:
    logo: chapters/images/logos/tuw-geo_eodc_logo_horizontal.png
  sidebar:
    logo: chapters/images/logos/tuw-geo_eodc_logo_vertical.png
bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#006699"
    title-block-banner-color: white

execute:
  freeze: auto
  cache: true
  keep-ipynb: true
  eval: true
