project:
  type: book
  pre-render: 
    - make kernel
    - make data
  post-render: make post-render

book:
  title: "notebooks4eo"
  author: ""
  date: "10/7/2024"
  chapters:
    - index.qmd
    - chapters/01_classification.qmd
    - chapters/02_floodmapping.qmd
    - chapters/references.qmd
  navbar: 
    logo: assets/images/tuw-geo-logo.svg
  sidebar:
    logo: assets/images/tuw-geo-logo.svg
bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#006699"
    title-block-banner-color: white