name: eo-datascience
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - mamba
  - jupyter
  - jupyter-cache
  - nbformat
  - pre-commit
  - nbstripout
  - pytest
  - jupyter-book
  - sphinx-pythia-theme
