name: Quarto Build
inputs:
  USER_HSAF:
    required: true
  PASS_HSAF:
    required: true
  USER_WEKEO:
    required: true
  PASS_WEKEO:
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      env:
        PREFIX: ./chapters/courses/environmental-remote-sensing/unit_01/
      run: |
        touch $PREFIX.env
        echo USER_HSAF = ${{ inputs.USER_HSAF }} >> $PREFIX.env
        echo PASS_HSAF = ${{ inputs.PASS_HSAF }} >> $PREFIX.env
        echo USER_WEKEO = ${{ inputs.USER_WEKEO }} >> $PREFIX.env
        echo PASS_WEKEO = ${{ inputs.PASS_WEKEO }} >> $PREFIX.env

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Jupyter and Jupyter-cache
      shell: bash
      run: pip install jupyter jupyter-cache

    - name: Conda Cache Environment
      uses: actions/cache@v4
      with:
        path: |
          ./.conda_envs
          /home/runner/.local/share/jupyter/kernels
        key: ${{ runner.os }}-env-${{ hashFiles('./notebooks/**/*.yml') }}
        restore-keys: ${{ runner.os }}-env-

    - name: Jupyter Cache Environment
      uses: actions/cache@v4
      with:
        path: |
          ./chapters/.jupyter_cache
          ./chapters/courses/.jupyter_cache
          ./chapters/courses/environmental-remote-sensing/.jupyter_cache
          ./chapters/courses/environmental-remote-sensing/unit_01/.jupyter_cache
          ./chapters/courses/microwave-remote-sensing/.jupyter_cache
          ./chapters/courses/microwave-remote-sensing/unit_01/.jupyter_cache
          ./chapters/courses/microwave-remote-sensing/unit_02/.jupyter_cache
          ./chapters/courses/microwave-remote-sensing/unit_03/.jupyter_cache
          ./chapters/templates/.jupyter_cache
          ./chapters/tutorials/.jupyter_cache
        key: ${{ runner.os }}-jupyter
        restore-keys: ${{ runner.os }}-jupyter

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
