name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - aiohttp
  - black
  - cartopy
  - dask
  - datashader
  - earthaccess
  - ffmpeg
  - fiona
  - flake8-nb
  - folium
  - geoviews
  - hda
  - hvplot
  - isort
  - importlib-metadata=4.13.0
  - jupyter==1.1.1
  - jupyterlab==4.2.5
  - jupyterlab_server==2.27.3
  - jupyterlab_widgets==3.0.13
  - jupyter-server-proxy
  - jupyter_bokeh
  - lxml
  - mamba
  - matplotlib
  - nbqa
  - openpyxl
  - pandas
  - pip
  - pyogrio
  - python=3.13
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - statsmodels
  - zarr=2.18.4
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
      - pre-commit
      - pyswi
      - pyviz_comms==3.0.4
      - ./environmental-remote-sensing
