name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - mamba
  - jupyter
  - pandas
  - matplotlib
  - hvplot
  - datashader
  - geoviews
  - cartopy
  - dask
  - jupyter_bokeh
