name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - mamba
  - jupyter
  - hda
  - ffmpeg
  - folium
  - pandas
  - lxml
  - matplotlib
  - hvplot
  - datashader
  - geoviews
  - cartopy
  - dask
  - pyogrio
  - rioxarray
  - jupyter_bokeh
  - requests
  - statsmodels
  - aiohttp
  - scikit-learn
  - zarr=2.18.4
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
      - pre-commit
      - pyswi
