name: Auto Render Notebooks

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Convert changed QMD files to notebooks
        run: |
          git fetch origin main
          CHANGED_QMDS=$(git diff --name-only origin/main -- 'chapters/*.qmd' || true)

          for file in $CHANGED_QMDS; do
            filename=$(basename "$file" .qmd)
            quarto convert "$file" --to ipynb --output "notebooks/${filename}.ipynb"
          done

      - name: Commit and push notebooks
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git add notebooks/*.ipynb || true
          git diff --cached --quiet || git commit -m "Auto-render notebooks from changed QMD files"
          git push
