on:
  workflow_dispatch:
  push:
    tags: [v*]
    # When a tag like v2024.11.27 is created, the workflow will be triggered
    # Should follow https://calver.org/ for versioning

name: Pythia Publish

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-quarto.yaml
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pythia Book
        uses: actions/checkout@v4
        with:
          repository: ProjectPythia/eo-datascience-cookbook
          path: pythia
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Build Quarto Book
        uses: ./.github/actions/build-quarto

      - name: Commit Files Pythia Book
        run: |
          python -m pip install .
          pythia_convert --out ./pythia
          ./copy-pythia.sh ./pythia
          cd ./pythia
          pre-commit run --all-files
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Quarto output" || echo "No changes to commit"
          git push || echo "No changes to commit"
