on:
  workflow_dispatch:
  push:
    tags: [v*]
    # When a tag like v2024.11.27 is created, the workflow will be triggered
    # Should follow https://calver.org/ for versioning

name: Pythia Publish

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quarto Book
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - name: Checkout Pythia Book
        uses: actions/checkout@v4
        with:
          repository: ProjectPythia/eo-datascience-cookbook
          path: pythia
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Build Quarto Book
        uses: ./.github/actions/build-quarto
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_HSAF: ${{ secrets.USER_HSAF }}
          PASS_HSAF: ${{ secrets.PASS_HSAF }}
          USER_WEKEO: ${{ secrets.USER_WEKEO }}
          PASS_WEKEO: ${{ secrets.PASS_WEKEO }}

      - name: Format Pythia Style
        continue-on-error: true
        run: |
          python -m pip install . pre-commit
          pythia_convert --out ./pythia
          ./copy-pythia.sh ./pythia
          cd ./pythia
          pre-commit install
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          pre-commit run

      - name: Commit Pythia Book
        run: |
          cd ./pythia
          git add .
          git commit --no-verify -m  "Quarto output"  || echo "No changes to commit"
          git push || echo "No changes to commit"
