on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

permissions:
  contents: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quarto Book
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - name: Build Quarto Book
        uses: ./.github/actions/build-quarto
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_HSAF: ${{ secrets.USER_HSAF }}
          PASS_HSAF: ${{ secrets.PASS_HSAF }}
          USER_WEKEO: ${{ secrets.USER_WEKEO }}
          PASS_WEKEO: ${{ secrets.PASS_WEKEO }}

      - name: Publish Quarto Book
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          render: false
          target: gh-pages
