on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

permissions:
  contents: write
  pages: write

jobs:
  build:
    uses: ./.github/workflows/build-quarto.yaml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish Quarto Book
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          render: false
          target: gh-pages
