on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Quarto Book
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Jupyter
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install jupyter jupyter-cache

      - name: Cache Environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/jupyter/kernels
            ~/.cache/pip
            ./.conda_envs
            '**/.jupyter_cache/**'
          key: ${{ runner.os }}-env-${{ hashFiles('./notebooks/**/*.yml') }}
          restore-keys: ${{ runner.os }}-env-

      - name: Render and Publish
        id: setup-python
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Binder Build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }}
          REPO2DOCKER_EXTRA_ARGS: --subdir notebooks
